### ISSUE TITLE
Exception on close

### ISSUE THREAD

**Issue by julianoes** [Pat-Carter/stream2chromecast#13]
Hi,

firstly, thanks for the great tool, love it!

Secondly, I see a small improvement:
Currently (cb331489c3777bb8e6e0f473972018764e7df77c) on Ubuntu 16.04 I can stop the script by pressing Ctrl+C, however, it doesn't exit cleanly and prints an exception:

```
waiting for player to finish - press ctrl-c to stop...
^C
stopping...
done
----------------------------------------
Exception happened during processing of request from ('192.168.0.xxx', xxxxx)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

I'm aware that this is just a cosmetic and not a functional "bug", more a nice to have :).

**Comment by Pat-Carter** [comment]
Hi Julian,

Thanks for the comment. I'll take a look and see if I can tidy that up. Probably that will be at the weekend.

cheers,

Pat

**Comment by Pat-Carter** [comment]
OK - that should be done now.

cheers,

Pat
