### ISSUE TITLE
When using transconde accept HTTPS urls as input

### ISSUE THREAD

**Issue by jsalatiel** [Pat-Carter/stream2chromecast#19]
It would be nice if we could transcode using a https url ( self signed ) as input instead of a localfile.

**Comment by Pat-Carter** [comment]
Are we talking about the playurl option?

I'm afraid transcode can only operate on local files at the moment.

I'll give it some thought, but I think ffmpeg might need to be able to read the entire file before converting it.

**Comment by jsalatiel** [comment]
HI Pat, i dont know this playurl option. Is it from ffmpeg ?
Ffmpeg is able to transcode  remote files, actually i changed your code ( i am no programmer, so the code is a mess lol) and it worked.
I did fmpeg_command = self.transcoder_command % ("https://someStreamHere", config['ffmpeg_preset'], config['ffmpeg_bitrate']) and basically changed the get_mimetype method to :

```
def get_mimetype(filename, ffprobe_cmd=None):
mimetype = "video/x-matroska"
     return mimetype
```

and , of course,  changes to the play method not check if the file exists.

So, what i think is needed is:
check if a local file, if its not ,check if it is a supported url (http/https), if none return not found.
But if it is a valid url,  the user has to pass the mimetype in command line.

Well, i think this is the best i can help with =)

Keep improving this software, it is just amazing !

**Comment by jsalatiel** [comment]
lol , i didn't know this option and 'grep' was not my friend.

Play remote file using a URL (e.g. a web video):
    stream2chromecast.py -playurl <URL>


I am gonna test it

**Comment by jsalatiel** [comment]
Well, i did a small test here and it does not accept urls with user and password , like 
'https://user:password@server:port/xyz/abc.mp4' and when removing the user and password i get

```
Traceback (most recent call last):
  File "./stream2chromecast.py", line 672, in <module>
    run()
  File "./stream2chromecast.py", line 662, in run
    playurl(arg2, device_name=device_name)                          
  File "./stream2chromecast.py", line 491, in playurl
    sys.exit("HTTP error:" + resp.status + " - " + resp.reason)
TypeError: cannot concatenate 'str' and 'int' objects

```

**Comment by Pat-Carter** [comment]
OK - thanks. I'll take a look.

The playurl option was only really added to aid in some problem diagnosis in another issue. It just tells the device to get the file from the address. The file doesn't come through the PC.

It looks like we might be able to do something with the transcode option, though but it might be a bit slow. I guess it would depend on the speed of the internet connection.

I'll take a look as soon as I can. I'm quite busy at the moment, so it might be few days.
