### ISSUE TITLE
The script crashes when you power down your chromecast

### ISSUE THREAD

**Issue by Ranix** [Pat-Carter/stream2chromecast#26]
Hi Pat

im in love whit your code!!

but this error ocurre when your turn off the chromecast. In this case my dog unplug the conector from the tv, so all shots down, when i try to reconnect everything("Turns the tv and play the movie again") the terminal pop up this message.

i hope works, Regards. 

stopping...
done
Traceback (most recent call last):
  File "./stream2chromecast.py", line 733, in <module>
    run()
  File "./stream2chromecast.py", line 729, in run
    subtitles_port=subtitles_port, subtitles_language=subtitles_language)
  File "./stream2chromecast.py", line 487, in play
    load(cast, url, req_handler.content_type, sub, subtitles_language)
  File "./stream2chromecast.py", line 510, in load
    cast.stop()
  File "/./stream2chromecast/cc_media_controller.py", line 427, in stop
    self.control("STOP")         
  File "/./stream2chromecast/cc_media_controller.py", line 338, in control
    self.connect("receiver-0")
  File "/./stream2chromecast/cc_media_controller.py", line 232, in connect
    self.send_data(namespace, data)
  File "/./stream2chromecast/cc_media_controller.py", line 112, in send_data
    self.sock.write(msg)
  File "/usr/lib/python2.7/ssl.py", line 661, in write
    return self._sslobj.write(data)
socket.error: [Errno 110] Connection timed out
----------------------------------------
Exception happened during processing of request from ('192.168.1.76', 51662)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "./stream2chromecast.py", line 192, in finish
    return BaseHTTPServer.BaseHTTPRequestHandler.finish(self)
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception KeyboardInterrupt in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by Pat-Carter** [comment]
OK - I'll look at catching the Connection Timed out error when the Chromecast disappears from the network.

I have some other changes that I'm currently in the process of testing, but I'll try to do something about this one afterwards.
