### ISSUE TITLE
A Chromecast with Guest Mode enabled triggers a socket.error

### ISSUE THREAD

**Issue by 8none1** [Pat-Carter/stream2chromecast#4]
I have two Chromecasts on my LAN.  I reconfigured one to use Guest Mode.  When doing a "-status" I get this error:

$ ./stream2chromecast.py -status
searching the network for a Chromecast device
Traceback (most recent call last):
  File "./stream2chromecast.py", line 508, in <module>
    run()
  File "./stream2chromecast.py", line 470, in run
    get_status()
  File "./stream2chromecast.py", line 417, in get_status
    print CCMediaController().get_status()
  File "/home/will/source/stream2chromecast/stream2chromecast/cc_media_controller.py", line 24, in __init__
    self.host, name = cc_device_finder.find_device(name=device_name)
  File "/home/will/source/stream2chromecast/stream2chromecast/cc_device_finder.py", line 141, in find_device
    return hosts[0], get_device_name(hosts[0])
  File "/home/will/source/stream2chromecast/stream2chromecast/cc_device_finder.py", line 80, in get_device_name
    conn.request("GET", "/ssdp/device-desc.xml")
  File "/usr/lib/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 778, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by 8none1** [comment]
Oh, and when I turn Guest Mode off again the error goes away

**Comment by Pat-Carter** [comment]
OK - thanks. I hadn't tried Guest Mode.

**Comment by Pat-Carter** [comment]
I've just run a quick test against my Chromecast in Guest mode and that seems to work OK. I only have the single Chromecast though, so I'm wondering if the issue has something to do with multiple Chromecasts. 

Currently, it only works against the first device it finds - which isn't very good. 

Specifying a named device was on the to-do list. Most of the functionality is there in the cc_device_finder.py module to allow specifying a device by name. 

It shouldn't be too big a step to provide a -device-name parameter in the stream2chromecast.py script. 

I'll pick this up in the week.

**Comment by bparker06** [comment]
Any progress on this? I'd really like to be able to specify the chromecast device to use.

**Comment by Pat-Carter** [comment]
Sorry. Yes, I'd forgotten about this.  I'm on it now.

**Comment by Pat-Carter** [comment]
I've added a -devicename parameter. 

Could you give it a try and let me know how it goes, please? I only have one device, but I've tested as far as I can.

The syntax should now be:-

**Comment by bparker06** [comment]
How do I find the names? The -status option still only shows me 1 device but there are several on my network.

**Comment by Pat-Carter** [comment]
The status command gets the status of the named device, or the first one it finds on the network if no name is specified.

The name should appear on the screen that the device is attached to.

So, for example, my device is a called "CEEFAX".

If I run:-
stream2chromecast.py -devicename CEEFAX -status

I get:-
found device: CEEFAX
Device: CEEFAX
{'host': '192.168.1.10', 'client': ('192.168.1.18', 60738), 'media_status': None, 'receiver_status': None}

Are any of your devices in Guest Mode?

**Comment by bparker06** [comment]
None of my devices are actual Chromecasts, so they don't 'obviously' advertise their names. For example Amazon Fire TV, Nexus Player/Shield, BubbleUPnPServer, they all work with Cast-enabled apps but I don't know how to find (or even change) their names independently. But I think I would be more interested in a search function that shows all devices so I could choose it that way.

**Comment by Pat-Carter** [comment]
OK - hang on a bit, I'll see if I can put together a list function.

**Comment by Pat-Carter** [comment]
OK - I've added a search function.

Can you try running the following, please?:-

stream2chromecast.py -devicelist

...that should search for 10 seconds and report back all the devices that respond.

**Comment by bparker06** [comment]
$ python2 ./stream2chromecast.py -devicelist
Searching for devices, please wait...
3 devices found
192.168.254.5 : SHIELD
192.168.254.1 : Nexus Player
192.168.254.2 : 

Looks like the FireTV box is the blank one, so not sure how I would select that device. Is it possible to support non-Google devices or audio-only devices? For example BubbleUPnP on my phone shows my home theather receiver as well as Kodi running on my Shield as other devices I can cast to... in addition to the 3 listed above.

I just tried to play a file to the SHIELD device and I get this error:

$ python2 ./stream2chromecast.py -devicename SHIELD ~/test.mp4
Playing:  /home/bp/test.mp4
OS identifies the mimetype as : video/mp4
Traceback (most recent call last):
  File "./stream2chromecast.py", line 546, in <module>
    run()
  File "./stream2chromecast.py", line 542, in run
    play(args[0], device_name=device_name)        
  File "./stream2chromecast.py", line 373, in play
    cast = CCMediaController(device_name=device_name)
  File "/home/bp/stream2chromecast/cc_media_controller.py", line 24, in __init__
    self.host, name = cc_device_finder.find_device(name=device_name)
  File "/home/bp/stream2chromecast/cc_device_finder.py", line 146, in find_device
    ip_addr = check_cache(name)
  File "/home/bp/stream2chromecast/cc_device_finder.py", line 109, in check_cache
    hostname, host  = line.strip().split("\t", 1)
ValueError: need more than 1 value to unpack

**Comment by Pat-Carter** [comment]
I think I can see what's happened.

When the devicename is specified, it searches the network and waits for 5 seconds for all of the devices to respond.

For every device that responds, it saves the name & ip address to a cache file. This is to try to save doing a network search on subsequent uses of the device.

Unfortunately I didn't consider the possibility of devices with no hostname.

I've committed a fix to this. Could you try the latest version and see what happens, please?

Also, I'll see if I can put together a function to specify a device by IP address as well as by name.

**Comment by bparker06** [comment]
Now I get this error:

$ python2 ./stream2chromecast.py -devicename SHIELD ~/test.mp4
Playing:  /home/bp/test.mp4
OS identifies the mimetype as : video/mp4
found device: SHIELD
Device: SHIELD
my ip address:  192.168.254.6
Serving media from:  http://192.168.254.6:37093/home/bp/test.mp4
192.168.254.5 - - [25/Jun/2016 14:35:53] "GET /home/bp/test.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.254.5', 36084)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

On the TV it shows a progress bar for several seconds and then just sits on a blank screen with the cast logo forever.

**Comment by Pat-Carter** [comment]
OK - it looks like we've got the device running the Media Player app and requesting the file but not handling it properly.

One thing I've found is that not all MP4 files are streamable.

Could you try using the -transcode parameter, please? 

So, something like:-

./stream2chromecast.py -devicename SHIELD -transcode ~/test.mp4

**Comment by bparker06** [comment]
With that, ffmpeg (3.0.2 on archlinux) complains: "Unknown encoder 'libfdk_aac'" and then it quits. If I change the source to use just "aac" instead, then I get the same error:

http://pastebin.com/raw/YGc8vfTa

**Comment by Pat-Carter** [comment]
OK - thanks for trying that.

I'll have to pick this up tomorrow, I'm afraid.

**Comment by Pat-Carter** [comment]
If you get the chance, could you try an MP3 file and see if that goes through, please? It shouldn't need transcoding.

If that works, there's a streamable mp4 sample video at http://techslides.com/demos/sample-videos/small.mp4 - again, that shouldn't need transcoding.

**Comment by bparker06** [comment]
Same error as before on both, "Broken pipe". Only difference is with the mp3, my device shows a placeholder square for album art on the loading screen.

**Comment by Pat-Carter** [comment]
I'm afraid I'm a bit stumped. I don't have access to a SHIELD unfortunately.

The broken pipe just means that the device has closed the connection - for some reason.

The only thing I can think of doing, is - if you like, you could display the messages going to and from the device.

There are a couple of commented out debugging lines in cc_media_controller.py.

Line 66 & lines 93, 94 have print commands. If you remove the '#' comment character, we can see the messages going backward and forward. This might give a clue.

**Comment by bparker06** [comment]
Here is what that shows: http://dpaste.com/3X34B3Q

The same thing happens with the Nexus Player as well, haven't tried the Amazon Fire as it's disconnected right now.

**Comment by Pat-Carter** [comment]
Thanks. I can't see anything obviously wrong with that output though.

I'll carry on looking and see if there's any way I can recreate it.

In the meantime, have you seen pychromecast? 

https://github.com/balloob/pychromecast

...it might be interesting to see if the same issues exist with that.

**Comment by bparker06** [comment]
I haven't, but apparently it works for me. I followed the example on that page to play Big Buck Bunny and it worked right away.

**Comment by Pat-Carter** [comment]
I've been thinking about this one. My current theory is that the device doesn't like the response from our HTTP server for some reason. 

The way it works is that we set up a temporary HTTP server on a spare port on the PC to serve the media file and then send a load command to the media player with a URL pointing back to the PC.

Perhaps it doesn't like the fact that we weren't sending a Content-Length HTTP header with the response.

So, I've tried adding a Content-Length to the response. Could you try grabbing the latest version and seeing how that goes, please?

I've only set it up for non-transcoded files at the moment because, as the transcoding works in real-time, we don't know the final length of the response at the start of the response.

If that still doesn't work, could you also try the -playurl option and let me know how that goes, please?

e.g. 

python stream2chromecast.py -playurl https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
