### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by Go3Team** [Pat-Carter/stream2chromecast#42]
I'm trying to automate stream2chromecast using openhab & apache.  

If I run the php file direct from the command line it works fine.  If I try to run it as a different user (from browser), it errors with this:

    Traceback (most recent call last):
      File "/usr/bin/stream2chromecast", line 798, in <module>
        run()
      File "/usr/bin/stream2chromecast", line 794, in run
        subtitles_port=subtitles_port, subtitles_language=subtitles_language)
      File "/usr/bin/stream2chromecast", line 418, in play
        save_pid(cast.host)
      File "/usr/bin/stream2chromecast", line 325, in save_pid
        with open(pid_file, "w") as pidfile:
    IOError: [Errno 13] Permission denied: '/tmp/stream2chromecast_192.168.2.97.pid'

Any ideas?

Thanks.

**Comment by Pat-Carter** [comment]
I would guess that your Apache user maybe doesn't have permissions to write
to /tmp.
