### ISSUE TITLE
I can stream but no devices found with devicelist option

### ISSUE THREAD

**Issue by JuGuSm** [Pat-Carter/stream2chromecast#68]
Hi,

I can stream files but I can't find my device (GH mini) with the command "stream2chromecast.py -devicelist".

**Comment by Carter90** [comment]
Have you pulled the code in the last week? Pat fixed it for the Chromecasts after the first generation.

**Comment by nlienard** [comment]
Got same issue after a fresh git clone today.

     thoht@osmc:~$ git clone https://github.com/bronche/stream2chromecast
     Clonage dans 'stream2chromecast'...
     remote: Counting objects: 330, done.
     remote: Total 330 (delta 0), reused 0 (delta 0), pack-reused 330
     Réception d'objets: 100% (330/330), 136.10 KiB | 0 bytes/s, fait.
     Résolution des deltas: 100% (179/179), fait.
     Vérification de la connectivité... fait.

     thoht@osmc:~$ cd stream2chromecast/
     thoht@osmc:~/stream2chromecast$ ls
     cc_device_finder.py  cc_media_controller.py  cc_message.py  LICENSE  README.md       stream2chromecast.py


     thoht@osmc:~/stream2chromecast$ python stream2chromecast.py -devicelist
     Searching for devices, please wait...
     0 devices found

**Comment by Pat-Carter** [comment]
I think that might be a different repository.

 thoht@osmc:~$ git clone https://github.com/bronche/stream2chromecast

**Comment by nlienard** [comment]
omg, what is the official repo ? i'm lost now.

**Comment by Pat-Carter** [comment]
Well, this one I guess :-)

Pat-Carter/stream2chromecast rather than bronche.

That one seems to be a fork.

**Comment by nlienard** [comment]
just did a git clone one this repo

thoht@osmc:~/stream2chromecast$ python stream2chromecast.py -devicelist
Searching for devices, please wait...
Sending mDNS query

HAD TO CONTROL C after 10mn

^CTraceback (most recent call last):
  File "stream2chromecast.py", line 798, in <module>
    run()
  File "stream2chromecast.py", line 790, in run
    list_devices()
  File "stream2chromecast.py", line 661, in list_devices
    device_ips = cc_device_finder.search_network(device_limit=None, time_limit=10)
  File "/home/thoht/stream2chromecast/cc_device_finder.py", line 52, in search_network
    addrs += search_network_mdns(device_limit=device_limit, time_limit=time_limit)
  File "/home/thoht/stream2chromecast/cc_device_finder.py", line 162, in search_network_mdns
    data, addr = sock.recvfrom(1024)
KeyboardInterrupt
