### ISSUE TITLE
Only finding one of my chromecasts

### ISSUE THREAD

**Issue by tonsV2** [Pat-Carter/stream2chromecast#9]
I have two chromecasts on my network. One called Living room which is detected by running ./stream2chromecast.py -status.  When I try to specify the device name it fails and the second one isn't found either.

[tons@mini stream2chromecast]$ ./stream2chromecast.py -status
searching the network for a Chromecast device
device name: Living room
{'host': '192.168.0.9', 'client': ('192.168.0.3', 55300), 'media_status': None, 'receiver_status': None}
[tons@mini stream2chromecast]$ ./stream2chromecast.py -devicename 'Living room' -status
searching the network for: Living room
Traceback (most recent call last):
  File "./stream2chromecast.py", line 572, in <module>
    run()
  File "./stream2chromecast.py", line 542, in run
    get_status(device_name=device_name)
  File "./stream2chromecast.py", line 460, in get_status
    print CCMediaController(device_name=device_name).get_status()
  File "/home/tons/stream2chromecast/cc_media_controller.py", line 25, in __init__
    self.host = self.get_device(device_name)
  File "/home/tons/stream2chromecast/cc_media_controller.py", line 52, in get_device
    host, name = cc_device_finder.find_device(name=device_name)
  File "/home/tons/stream2chromecast/cc_device_finder.py", line 161, in find_device
    result_map[get_device_name(host)] = host
  File "/home/tons/stream2chromecast/cc_device_finder.py", line 80, in get_device_name
    conn.request("GET", "/ssdp/device-desc.xml")
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
[tons@mini stream2chromecast]$ ./stream2chromecast.py -status
searching the network for a Chromecast device
device name: Living room
{'host': '192.168.0.9', 'client': ('192.168.0.3', 55310), 'media_status': None, 'receiver_status': None}
[tons@mini stream2chromecast]$ ./stream2chromecast.py -devicename 'Living room' -status
searching the network for: Living room
Traceback (most recent call last):
  File "./stream2chromecast.py", line 572, in <module>
    run()
  File "./stream2chromecast.py", line 542, in run
    get_status(device_name=device_name)
  File "./stream2chromecast.py", line 460, in get_status
    print CCMediaController(device_name=device_name).get_status()
  File "/home/tons/stream2chromecast/cc_media_controller.py", line 25, in __init__
    self.host = self.get_device(device_name)
  File "/home/tons/stream2chromecast/cc_media_controller.py", line 52, in get_device
    host, name = cc_device_finder.find_device(name=device_name)
  File "/home/tons/stream2chromecast/cc_device_finder.py", line 161, in find_device
    result_map[get_device_name(host)] = host
  File "/home/tons/stream2chromecast/cc_device_finder.py", line 80, in get_device_name
    conn.request("GET", "/ssdp/device-desc.xml")
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
[tons@mini stream2chromecast]$ ./stream2chromecast.py -devicename Bedroom -status
searching the network for: Bedroom
Traceback (most recent call last):
  File "./stream2chromecast.py", line 572, in <module>
    run()
  File "./stream2chromecast.py", line 542, in run
    get_status(device_name=device_name)
  File "./stream2chromecast.py", line 460, in get_status
    print CCMediaController(device_name=device_name).get_status()
  File "/home/tons/stream2chromecast/cc_media_controller.py", line 25, in __init__
    self.host = self.get_device(device_name)
  File "/home/tons/stream2chromecast/cc_media_controller.py", line 52, in get_device
    host, name = cc_device_finder.find_device(name=device_name)
  File "/home/tons/stream2chromecast/cc_device_finder.py", line 161, in find_device
    result_map[get_device_name(host)] = host
  File "/home/tons/stream2chromecast/cc_device_finder.py", line 80, in get_device_name
    conn.request("GET", "/ssdp/device-desc.xml")
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by Pat-Carter** [comment]
Hi. Could you try connecting with the IP address instead of the the devicename, please.

e.g. ./stream2chromecast.py -devicename 192.168.0.9 -status

Do you have anything else on your network that might be responding to a service discovery broadcast? I'm wondering if it is asking some other device for its name and getting a connection refused from that.

**Comment by Norbator** [comment]
Hi. 
I don't want to pirate tonsV2 thread but I just encountered the same problem a few minutes ago...
I have 4 audio chromecasts on my network. 
`./stream2chromecast.py -devicelist` fails with `socket.error: [Errno 111] Connection refused`
`./stream2chromecast.py -devicename 'HP HK Onyx' -status` fails with same error
`./stream2chromecast.py -devicename 192.168.10.25 -status` is successful
`ip_addr: 192.168.10.25 device name: HP HK Onyx
{'host': '192.168.10.25', 'client': ('192.168.10.100', 48456), 'media_status': None, 'receiver_status': None}`

Running [https://gist.github.com/provegard/1435555](url) shows a lot of devices answering to SSDP protocol. 
`Sending M-SEARCH...
Received HTTP/1.1 200 OK from ('192.168.10.1', 1900)
Received HTTP/1.1 200 OK from ('192.168.10.102', 53610)
Received HTTP/1.1 200 OK from ('192.168.10.23', 44522)
Received HTTP/1.1 200 OK from ('192.168.10.29', 41975)
Received HTTP/1.1 200 OK from ('192.168.10.25', 43420)
Received HTTP/1.1 200 OK from ('192.168.10.101', 1900)`
[...]

Hope it helps.

**Comment by Pat-Carter** [comment]
Thanks - I'm guessing the following happens:-

1. Network things respond to a search.
2. We try to connect and ask for the chromecast device name.
3. Things refuse to let us connect so we bail out.

I've updated  cc_device_finder.py to cope with errors when connecting to get the device name.

Could you give it a try and let me know what happens, please?

thanks 
 - Pat

**Comment by Norbator** [comment]
It works fine!
`./stream2chromecast.py -devicelist`
`Searching for devices, please wait...`
`5 devices found`
`192.168.10.102 :` 
`192.168.10.23 : @Salon - Onkyo (Optical)`
`192.168.10.25 : HP HK Onyx`
`192.168.10.29 : @SdB - HP CT2`
`192.168.10.24 : @Cuisine - HP CT2`

192.168.10.102 is an intruder: it's a Samsung TV Set!  

`./stream2chromecast.py -devicename 'HP HK Onyx' -status`
`Device name response: HP HK Onyx`
`found device in cache: HP HK Onyx`
`device name: HP HK Onyx`
`{'host': '192.168.10.25', 'client': ('192.168.10.100', 50008), 'media_status': None, 'receiver_status': None}`

**Comment by Pat-Carter** [comment]
Excellent.

thanks!

:-)

**Comment by tonsV2** [comment]
I can also confirm that it works now. Thanks!
